#!/usr/bin/env python3

import json
import yaml
import glob

groups = {}

for hostfilename in glob.glob('./host_vars/*.yml'):
    with open(hostfilename, 'r') as hostfile:
        # Using yaml.CLoader - https://pyyaml.org/wiki/PyYAMLDocumentation
        host = yaml.load(hostfile, Loader=yaml.CLoader)
        for hostgroup in host['host_groups']:
            if hostgroup not in groups.keys():
                groups[ hostgroup ] = { 'hosts': [] }
            groups[ hostgroup ]['hosts'].append( host['host_fqdn'] )

print(json.dumps(groups))

